"""
Compare GAMA and pure-Python backend runtimes from experiment log files.

The script expects result directories produced by run_experiment.py.

Usage
-----
One scenario:

    docker-compose exec gym-agent python articles/neurips26/scripts/compare_backend_runtime.py \
        articles/neurips26/results/full_compliance__scenario_1_easy_det \
        articles/neurips26/results_python/full_compliance__scenario_1_easy_det

Several scenarios:

    docker-compose exec gym-agent python articles/neurips26/scripts/compare_backend_runtime.py \
        articles/neurips26/results/full_compliance__scenario_1_easy_det \
        articles/neurips26/results_python/full_compliance__scenario_1_easy_det \
        articles/neurips26/results/full_compliance__scenario_2_easy_stoch \
        articles/neurips26/results_python/full_compliance__scenario_2_easy_stoch

Arguments must come in pairs:
    <gama_result_dir> <python_result_dir>
"""

import glob
import os
import re
import sys

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


AGENT_ORDER = [
    "GlobalETC3",
    "GlobalETC5",
    "GlobalETC10",
    "GlobalUCRL3",
    "GlobalIMED-RL",
    "SemiLocalIMED-RL",
]


def latest_logfile(result_dir):
    """
    Return the most recent logfile in result_dir/regret/.

    Parameters
    ----------
    result_dir : str
        Experiment result directory.

    Returns
    -------
    str
        Path to the most recent logfile.
    """
    regret_dir = os.path.join(result_dir, "regret")
    logfiles = glob.glob(os.path.join(regret_dir, "logfile_*.txt"))

    if not logfiles:
        raise FileNotFoundError(f"No logfile found in {regret_dir}")

    return max(logfiles, key=os.path.getmtime)


def parse_runtime_log(logfile, backend, scenario):
    """
    Parse learner and oracle runtime lines from a logfile.

    Expected lines include:
        GlobalETC3 average runtime is ...
        Oracle average runtime per replicate is ...

    Parameters
    ----------
    logfile : str
        Path to a logfile generated by the experiment runner.
    backend : str
        Backend label, usually "GAMA" or "Python".
    scenario : str
        Scenario name inferred from the result directory.

    Returns
    -------
    list[dict]
        Runtime records.
    """
    rows = []

    learner_pattern = re.compile(r"^(.*?) average runtime is ([0-9.eE+-]+)")
    oracle_pattern = re.compile(
        r"^Oracle average runtime per replicate is ([0-9.eE+-]+)"
    )

    with open(logfile, "r") as f:
        for line in f:
            line = line.strip()

            match_learner = learner_pattern.match(line)
            if match_learner:
                agent = match_learner.group(1).strip()
                runtime = float(match_learner.group(2))

                if not agent.lower().startswith("oracle"):
                    rows.append(
                        {
                            "scenario": scenario,
                            "backend": backend,
                            "agent": agent,
                            "avg_runtime_seconds": runtime,
                            "logfile": os.path.basename(logfile),
                        }
                    )

            match_oracle = oracle_pattern.match(line)
            if match_oracle:
                runtime = float(match_oracle.group(1))
                rows.append(
                    {
                        "scenario": scenario,
                        "backend": backend,
                        "agent": "Oracle",
                        "avg_runtime_seconds": runtime,
                        "logfile": os.path.basename(logfile),
                    }
                )

    return rows


def compare_runtimes(gama_dir, python_dir):
    """
    Load GAMA and Python runtime logs and compute slowdown.

    Parameters
    ----------
    gama_dir : str
        Result directory for the GAMA backend.
    python_dir : str
        Result directory for the pure-Python backend.

    Returns
    -------
    tuple[pd.DataFrame, pd.DataFrame]
        Raw runtime records and pivoted summary table.
    """
    scenario = os.path.basename(os.path.normpath(gama_dir))

    gama_log = latest_logfile(gama_dir)
    python_log = latest_logfile(python_dir)

    rows = []
    rows.extend(parse_runtime_log(gama_log, "GAMA", scenario))
    rows.extend(parse_runtime_log(python_log, "Python", scenario))

    raw = pd.DataFrame(rows)

    pivot = raw.pivot_table(
        index=["scenario", "agent"],
        columns="backend",
        values="avg_runtime_seconds",
        aggfunc="mean",
    ).reset_index()

    if "GAMA" in pivot.columns and "Python" in pivot.columns:
        pivot["slowdown_GAMA_vs_Python"] = pivot["GAMA"] / pivot["Python"]

    return raw, pivot


def order_agents(df):
    """
    Sort agents in a stable, paper-friendly order.

    Parameters
    ----------
    df : pd.DataFrame
        DataFrame containing an ``agent`` column.

    Returns
    -------
    pd.DataFrame
        Sorted DataFrame.
    """
    present = list(df["agent"].unique())
    ordered = [a for a in AGENT_ORDER if a in present]
    remaining = sorted([a for a in present if a not in ordered])
    order = ordered + remaining

    df = df.copy()
    df["agent"] = pd.Categorical(df["agent"], categories=order, ordered=True)
    return df.sort_values("agent")


def plot_runtime_comparison(pivot, output_path):
    """
    Plot Python vs GAMA average runtime for a single scenario.

    Oracle is excluded from the plot because it is computed locally and is not
    representative of GAMA backend overhead.

    Parameters
    ----------
    pivot : pd.DataFrame
        Pivoted runtime table with Python and GAMA columns.
    output_path : str
        Path to save the figure.
    """
    df = pivot[pivot["agent"] != "Oracle"].copy()
    df = order_agents(df)

    agents = list(df["agent"].astype(str))

    x = np.arange(len(agents))
    width = 0.35

    fig, ax = plt.subplots(figsize=(11, 6))

    ax.bar(x - width / 2, df["Python"], width, label="Python")
    ax.bar(x + width / 2, df["GAMA"], width, label="GAMA")

    ax.set_xlabel("Agent")
    ax.set_ylabel("Average runtime per replicate (s)")
    ax.set_title("Backend runtime comparison")
    ax.set_xticks(x)
    ax.set_xticklabels(agents, rotation=15, ha="right")
    ax.legend()

    plt.tight_layout()
    plt.savefig(output_path, dpi=150)
    plt.close()

    print(f"[PLOT] Saved {output_path}")


def plot_runtime_slowdown_by_scenario(pivot, output_path):
    """
    Plot GAMA/Python slowdown by scenario and agent.

    This plot is intended for multi-scenario comparison. Oracle is excluded.

    Parameters
    ----------
    pivot : pd.DataFrame
        Combined pivoted runtime table.
    output_path : str
        Path to save the figure.
    """
    df = pivot[pivot["agent"] != "Oracle"].copy()

    if "slowdown_GAMA_vs_Python" not in df.columns:
        print("[PLOT] No slowdown column found. Skipping combined slowdown plot.")
        return

    scenarios = list(df["scenario"].unique())

    present_agents = list(df["agent"].unique())
    agents = [a for a in AGENT_ORDER if a in present_agents]
    agents += sorted([a for a in present_agents if a not in agents])

    x = np.arange(len(scenarios))
    width = 0.8 / max(len(agents), 1)

    fig, ax = plt.subplots(figsize=(14, 6))

    for i, agent in enumerate(agents):
        vals = []
        for scenario in scenarios:
            sub = df[(df["scenario"] == scenario) & (df["agent"] == agent)]
            vals.append(
                float(sub["slowdown_GAMA_vs_Python"].iloc[0])
                if len(sub)
                else np.nan
            )

        offsets = x + (i - len(agents) / 2 + 0.5) * width
        ax.bar(offsets, vals, width, label=agent)

    ax.set_xlabel("Scenario")
    ax.set_ylabel("Slowdown factor: GAMA / Python")
    ax.set_title("Backend slowdown across scenarios")
    ax.set_xticks(x)
    ax.set_xticklabels(scenarios, rotation=15, ha="right")
    ax.legend(title="Agent", ncol=2)

    plt.tight_layout()
    plt.savefig(output_path, dpi=150)
    plt.close()

    print(f"[PLOT] Saved {output_path}")


def validate_args(args):
    """
    Validate CLI arguments.

    The script expects one or more pairs:
        <gama_result_dir> <python_result_dir>
    """
    if len(args) < 2 or len(args) % 2 != 0:
        print(
            "Usage: python compare_backend_runtime.py "
            "<gama_result_dir_1> <python_result_dir_1> "
            "[<gama_result_dir_2> <python_result_dir_2> ...]"
        )
        sys.exit(1)


def main():
    args = sys.argv[1:]
    validate_args(args)

    pairs = [(args[i], args[i + 1]) for i in range(0, len(args), 2)]

    script_dir = os.path.dirname(os.path.abspath(__file__))
    output_dir = os.path.abspath(
        os.path.join(script_dir, "..", "backend_runtime_comparison")
    )
    os.makedirs(output_dir, exist_ok=True)

    all_raw = []
    all_pivots = []

    for gama_dir, python_dir in pairs:
        scenario = os.path.basename(os.path.normpath(gama_dir))

        print("=" * 60)
        print(f"Comparing scenario: {scenario}")
        print(f"GAMA:   {gama_dir}")
        print(f"Python: {python_dir}")
        print("=" * 60)

        raw, pivot = compare_runtimes(gama_dir, python_dir)

        all_raw.append(raw)
        all_pivots.append(pivot)

        csv_path = os.path.join(
            output_dir,
            f"runtime_comparison_{scenario}.csv",
        )
        pivot.to_csv(csv_path, index=False)
        print(f"[CSV] Saved {csv_path}")

        # If only one scenario is provided, create a direct Python vs GAMA plot.
        # If several scenarios are provided, only the global slowdown plot is created.
        if len(pairs) == 1:
            plot_path = os.path.join(
                output_dir,
                f"runtime_comparison_{scenario}.png",
            )
            plot_runtime_comparison(pivot, plot_path)

    combined_raw = pd.concat(all_raw, ignore_index=True)
    combined_pivot = pd.concat(all_pivots, ignore_index=True)

    raw_csv_path = os.path.join(output_dir, "runtime_comparison_all_raw.csv")
    pivot_csv_path = os.path.join(output_dir, "runtime_comparison_all_summary.csv")

    combined_raw.to_csv(raw_csv_path, index=False)
    combined_pivot.to_csv(pivot_csv_path, index=False)

    print(f"[CSV] Saved {raw_csv_path}")
    print(f"[CSV] Saved {pivot_csv_path}")

    # Always create the global slowdown plot.
    slowdown_path = os.path.join(
        output_dir,
        "runtime_slowdown_all_scenarios.png",
    )
    plot_runtime_slowdown_by_scenario(combined_pivot, slowdown_path)

    print("\n[DONE] Backend runtime comparison completed.")
    print(f"[INFO] Output directory: {output_dir}")


if __name__ == "__main__":
    main()